package com.xochitl.helloWorld.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "Cloths")
public class Cloth {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String cloth_id;
    @DynamoDBAutoGeneratedKey
    private String cloth_model;
    @DynamoDBAttribute
    private String cloth_color;
    @DynamoDBAttribute
    private String cloth_name;
    @DynamoDBAttribute
    private String cloth_size;
}
