package com.xochitl.helloWorld.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "cloths")
public class ClothModel {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private int id_cloth;
    @DynamoDBAttribute
    private String model;
    @DynamoDBAttribute
    private String color;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String size;
}
